name: chat_app
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  crypto: ^3.0.6
  convert: ^3.1.2
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.1
  http: ^1.3.0
  fluttertoast: ^8.2.12
  socket_io_client: ^3.1.1
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
